{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.shrhang.intangible.neoforge",
    "module": "1.21.1",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "1.21.1-1.0.3.jar",
          "url": "1.21.1-1.0.3.jar",
          "size": 27077,
          "sha512": "8a4d61cd01f08d3c8be5cb4fa1da5911a718560dbaaf7268bb108e8e59456c5fe58e39a3d64004fc9209f6d1f5ccaba00ff87c6e33aac62c38e82d5addb26db5",
          "sha256": "b826ede7f984f7ce0361dccd0287571c03f8758f46f6e92a974d3d8c87d00a17",
          "sha1": "99e7f5092bb0dfcb8a43c164cddef71c9a9d7e4c",
          "md5": "7833ff60928301d8e190255bc3dd6566"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "1.21.1-1.0.3.jar",
          "url": "1.21.1-1.0.3.jar",
          "size": 27077,
          "sha512": "8a4d61cd01f08d3c8be5cb4fa1da5911a718560dbaaf7268bb108e8e59456c5fe58e39a3d64004fc9209f6d1f5ccaba00ff87c6e33aac62c38e82d5addb26db5",
          "sha256": "b826ede7f984f7ce0361dccd0287571c03f8758f46f6e92a974d3d8c87d00a17",
          "sha1": "99e7f5092bb0dfcb8a43c164cddef71c9a9d7e4c",
          "md5": "7833ff60928301d8e190255bc3dd6566"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "1.21.1-1.0.3-sources.jar",
          "url": "1.21.1-1.0.3-sources.jar",
          "size": 15693,
          "sha512": "c39b6dea34280c2ff65ea832ef7e999de933004b486d95d59dc278cd9ed09912a27206f203a0222fb0cfe8597f6ac6ded0b7952cd006f43dccec210731c3ae4b",
          "sha256": "e628d05274cac36951b554f0ebbf16c8c6d0195fa6bf4b3a0bd678aeb3eab473",
          "sha1": "8e9ded0ce28112a5d7e18b820da61b55792a9dce",
          "md5": "5d953f5a3296c9a7adf068b04c03bdf2"
        }
      ]
    }
  ]
}
