{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.shrhang.intangible.neoforge",
    "module": "1.21.3-1.21.8",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "1.21.3-1.21.8-1.0.3.jar",
          "url": "1.21.3-1.21.8-1.0.3.jar",
          "size": 28247,
          "sha512": "d02655e87fd473b32a5139e83b11e402202dde6874bfb6fac5cb4699fe9077c4047b2c40e79dc870c3f38879bec808635600d9a05d411ffcb8b5d12f0d98eeb1",
          "sha256": "4e337434c3c7305cc179814c441299aa3e88af386ac579e6760bf4ea6a33cf7f",
          "sha1": "139c4de14611901b140a762cce0fc0db37355e7c",
          "md5": "9afd3edef090719bca4795ea3e0b5ecc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "1.21.3-1.21.8-1.0.3.jar",
          "url": "1.21.3-1.21.8-1.0.3.jar",
          "size": 28247,
          "sha512": "d02655e87fd473b32a5139e83b11e402202dde6874bfb6fac5cb4699fe9077c4047b2c40e79dc870c3f38879bec808635600d9a05d411ffcb8b5d12f0d98eeb1",
          "sha256": "4e337434c3c7305cc179814c441299aa3e88af386ac579e6760bf4ea6a33cf7f",
          "sha1": "139c4de14611901b140a762cce0fc0db37355e7c",
          "md5": "9afd3edef090719bca4795ea3e0b5ecc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "1.21.3-1.21.8-1.0.3-sources.jar",
          "url": "1.21.3-1.21.8-1.0.3-sources.jar",
          "size": 16025,
          "sha512": "fdf088910daee3e8c245492a0d17be41d8dd8591b732fdb641ee7af707df8345ae1aef6e97e8361900c33b61acebfe2d0e64f018814df2c1b9350ac76d285729",
          "sha256": "b007341a24d60558a7d25d69f7f5e454d381e9bd8c5173889686e19ddbf8ed89",
          "sha1": "d65696216d579c6eb9800d4967e20c584b959f30",
          "md5": "53193e22222f5f63bbeb894ed7c4fac1"
        }
      ]
    }
  ]
}
