{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.shrhang.create_food_filling.neoforge",
    "module": "1.21.1",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "1.21.1-1.5.2.jar",
          "url": "1.21.1-1.5.2.jar",
          "size": 43675,
          "sha512": "02992267d180f042d4b6327d88ddae734f354b6cb38e7c473bf8712927eb5646efe7585132ee7bc1ccd77d2b515b94f901a9c7c9a52968080eba7b8f972eba24",
          "sha256": "d4d319d952a98c6416d87c3cde8c0e75dcfdc2cdd8cec76ee5a2fddf2ee6dff7",
          "sha1": "3eef3fe74bf252eddffa2d28d27a54cfeb9d7b87",
          "md5": "8f33c251ff3b6d968f7a8d40f5a4a086"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+67"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.10-281"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "ponder-neoforge",
          "version": {
            "requires": "1.0.85+mc1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.52.0.422"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jupiter",
          "version": {
            "requires": "2.3.7-1.21.1-neoforge"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tooltips-reforged",
          "version": {
            "requires": "J25hE1s0"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.6-beta-37"
          }
        }
      ],
      "files": [
        {
          "name": "1.21.1-1.5.2.jar",
          "url": "1.21.1-1.5.2.jar",
          "size": 43675,
          "sha512": "02992267d180f042d4b6327d88ddae734f354b6cb38e7c473bf8712927eb5646efe7585132ee7bc1ccd77d2b515b94f901a9c7c9a52968080eba7b8f972eba24",
          "sha256": "d4d319d952a98c6416d87c3cde8c0e75dcfdc2cdd8cec76ee5a2fddf2ee6dff7",
          "sha1": "3eef3fe74bf252eddffa2d28d27a54cfeb9d7b87",
          "md5": "8f33c251ff3b6d968f7a8d40f5a4a086"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "1.21.1-1.5.2-sources.jar",
          "url": "1.21.1-1.5.2-sources.jar",
          "size": 22899,
          "sha512": "eedc0be571ab6a068765260a98ad6b26f196c11da9eb8ee3e12e6895cb6222c21d05cf71a16d3c26e4a859fc7e4a5116ca6799ac0a5cf1233c5a9484330288d8",
          "sha256": "bf84917b74c8a4a12c9e156a93df1730e5d6495c70b883a6da1da50ec5c55eb6",
          "sha1": "5cc168efa1051f45d22ec5ea634e44519c1161f7",
          "md5": "37ffc1c3e127cc6f46ef438ad2abf744"
        }
      ]
    }
  ]
}
